<?php
$dictionaryArray = array("dbversion"=>"1.0","overwritedb"=>"0","databasearray"=>array(array("orderId"=>"1","Dictionary"=>"Eyewitness Travel Phrase Book Chinese","ImageName"=>"images/1_Cover.png","BarCodeImage"=>"barcode/1_Barcode.png","Languages"=>"Chinese,English","BarCode"=>"9780241289358","DbPath"=>"datafiles/1_BVDTemplate.sqlite","region"=>"UK"),
							array("orderId"=>"2","Dictionary"=>"Eyewitness Travel Phrase Book Chinese","ImageName"=>"images/2_Cover.png","BarCodeImage"=>"barcode/2_Barcode.png","Languages"=>"Chinese,English","BarCode"=>"9781465462664","DbPath"=>"datafiles/2_BVDTemplate.sqlite","region"=>"US"),
                            array("orderId"=>"3","Dictionary"=>"Eyewitness Travel Phrase Book French","ImageName"=>"images/3_Cover.png","BarCodeImage"=>"barcode/3_Barcode.png","Languages"=>"French,English","BarCode"=>"9780241289365","DbPath"=>"datafiles/3_BVDTemplate.sqlite","region"=>"UK"),
                            array("orderId"=>"4","Dictionary"=>"Eyewitness Travel Phrase Book French","ImageName"=>"images/4_Cover.png","BarCodeImage"=>"barcode/4_Barcode.png","Languages"=>"French,English","BarCode"=>"9781465462671","DbPath"=>"datafiles/4_BVDTemplate.sqlite","region"=>"US"),
							array("orderId"=>"5","Dictionary"=>"Eyewitness Travel Phrase Book German","ImageName"=>"images/5_Cover.png","BarCodeImage"=>"barcode/5_Barcode.png","Languages"=>"French,English","BarCode"=>"9780241289372","DbPath"=>"datafiles/5_BVDTemplate.sqlite","region"=>"UK"),
							array("orderId"=>"6","Dictionary"=>"Eyewitness Travel Phrase Book German","ImageName"=>"images/6_Cover.png","BarCodeImage"=>"barcode/6_Barcode.png","Languages"=>"French,English","BarCode"=>"9781465462688","DbPath"=>"datafiles/6_BVDTemplate.sqlite","region"=>"US"),
							array("orderId"=>"7","Dictionary"=>"Eyewitness Travel Phrase Book Italian","ImageName"=>"images/7_Cover.png","BarCodeImage"=>"barcode/7_Barcode.png","Languages"=>"Italian,English","BarCode"=>"9780241289389","DbPath"=>"datafiles/7_BVDTemplate.sqlite","region"=>"UK"),
							array("orderId"=>"8","Dictionary"=>"Eyewitness Travel Phrase Book Italian","ImageName"=>"images/8_Cover.png","BarCodeImage"=>"barcode/8_Barcode.png","Languages"=>"Italian,English","BarCode"=>"9781465462800","DbPath"=>"datafiles/8_BVDTemplate.sqlite","region"=>"US"),
							array("orderId"=>"9","Dictionary"=>"Eyewitness Travel Phrase Book Spanish","ImageName"=>"images/9_Cover.png","BarCodeImage"=>"barcode/9_Barcode.png","Languages"=>"Spanish,English","BarCode"=>"9780241289402","DbPath"=>"datafiles/9_BVDTemplate.sqlite","region"=>"UK"),
							array("orderId"=>"10","Dictionary"=>"Eyewitness Travel Phrase Book Spanish","ImageName"=>"images/10_Cover.png","BarCodeImage"=>"barcode/10_Barcode.png","Languages"=>"Spanish,English","BarCode"=>"9781465462817","DbPath"=>"datafiles/10_BVDTemplate.sqlite","region"=>"US")));
							
    $dictionaryArraytest = array("dbversion"=>"1.0","overwritedb"=>"0","databasearray"=>array(array("orderId"=>"1","Dictionary"=>"Eyewitness Travel Phrase Book Chinese","ImageName"=>"images/1_Cover.png","BarCodeImage"=>"barcode/1_Barcode.png","Languages"=>"Chinese,English","BarCode"=>"9780241289358","DbPath"=>"datafiles/1_BVDTemplate.sqlite","region"=>"UK"),
							array("orderId"=>"2","Dictionary"=>"Eyewitness Travel Phrase Book Chinese","ImageName"=>"images/2_Cover.png","BarCodeImage"=>"barcode/2_Barcode.png","Languages"=>"Chinese,English","BarCode"=>"9781465462664","DbPath"=>"datafiles/2_BVDTemplate.sqlite","region"=>"US"),
                            array("orderId"=>"3","Dictionary"=>"Eyewitness Travel Phrase Book French","ImageName"=>"images/3_Cover.png","BarCodeImage"=>"barcode/3_Barcode.png","Languages"=>"French,English","BarCode"=>"9780241289365","DbPath"=>"datafiles/3_BVDTemplate.sqlite","region"=>"UK"),
                            array("orderId"=>"4","Dictionary"=>"Eyewitness Travel Phrase Book French","ImageName"=>"images/4_Cover.png","BarCodeImage"=>"barcode/4_Barcode.png","Languages"=>"French,English","BarCode"=>"9781465462671","DbPath"=>"datafiles/4_BVDTemplate.sqlite","region"=>"US"),
							array("orderId"=>"5","Dictionary"=>"Eyewitness Travel Phrase Book German","ImageName"=>"images/5_Cover.png","BarCodeImage"=>"barcode/5_Barcode.png","Languages"=>"French,English","BarCode"=>"9780241289372","DbPath"=>"datafiles/5_BVDTemplate.sqlite","region"=>"UK"),
							array("orderId"=>"6","Dictionary"=>"Eyewitness Travel Phrase Book German","ImageName"=>"images/6_Cover.png","BarCodeImage"=>"barcode/6_Barcode.png","Languages"=>"French,English","BarCode"=>"9781465462688","DbPath"=>"datafiles/6_BVDTemplate.sqlite","region"=>"US"),
							array("orderId"=>"7","Dictionary"=>"Eyewitness Travel Phrase Book Italian","ImageName"=>"images/7_Cover.png","BarCodeImage"=>"barcode/7_Barcode.png","Languages"=>"Italian,English","BarCode"=>"9780241289389","DbPath"=>"datafiles/7_BVDTemplate.sqlite","region"=>"UK"),
							array("orderId"=>"8","Dictionary"=>"Eyewitness Travel Phrase Book Italian","ImageName"=>"images/8_Cover.png","BarCodeImage"=>"barcode/8_Barcode.png","Languages"=>"Italian,English","BarCode"=>"9781465462800","DbPath"=>"datafiles/8_BVDTemplate.sqlite","region"=>"US"),
							array("orderId"=>"9","Dictionary"=>"Eyewitness Travel Phrase Book Spanish","ImageName"=>"images/9_Cover.png","BarCodeImage"=>"barcode/9_Barcode.png","Languages"=>"Spanish,English","BarCode"=>"9780241289402","DbPath"=>"datafiles/9_BVDTemplate.sqlite","region"=>"UK"),
							array("orderId"=>"10","Dictionary"=>"Eyewitness Travel Phrase Book Spanish","ImageName"=>"images/10_Cover.png","BarCodeImage"=>"barcode/10_Barcode.png","Languages"=>"Spanish,English","BarCode"=>"9781465462817","DbPath"=>"datafiles/10_BVDTemplate.sqlite","region"=>"US")));

?>
