<?php
$dictionaryArray = array("dbversion"=>"1.0","overwritedb"=>"0","databasearray"=>array(array("orderId"=>"1","Dictionary"=>"German English Bilingual Visual Dictionary","ImageName"=>"images/1_Cover.png","BarCodeImage"=>"barcode/1_Barcode.png","Languages"=>"German,English","BarCode"=>"9780241292457","DbPath"=>"datafiles/1_BVDTemplate.sqlite","region"=>"1"),
							array("orderId"=>"2","Dictionary"=>"German English Bilingual Visual Dictionary","ImageName"=>"images/2_Cover.png","BarCodeImage"=>"barcode/2_Barcode.png","Languages"=>"German","BarCode"=>"9781465459299","DbPath"=>"datafiles/2_BVDTemplate.sqlite","region"=>"2"),
                            array("orderId"=>"3","Dictionary"=>"Arabic English Bilingual Visual Dictionary","ImageName"=>"images/3_Cover.png","BarCodeImage"=>"barcode/3_Barcode.png","Languages"=>"Arabic,English","BarCode"=>"9780241292464","DbPath"=>"datafiles/3_BVDTemplate.sqlite","region"=>"1"),
                            array("orderId"=>"4","Dictionary"=>"Arabic English Bilingual Visual Dictionary","ImageName"=>"images/4_Cover.png","BarCodeImage"=>"barcode/4_Barcode.png","Languages"=>"Arabic,English","BarCode"=>"9781465459275","DbPath"=>"datafiles/4_BVDTemplate.sqlite","region"=>"2"),
							array("orderId"=>"5","Dictionary"=>"French English Bilingual Visual Dictionary","ImageName"=>"images/5_Cover.png","BarCodeImage"=>"barcode/5_Barcode.png","Languages"=>"French,English","BarCode"=>"9780241287286","DbPath"=>"datafiles/5_BVDTemplate.sqlite","region"=>"1"),
							array("orderId"=>"6","Dictionary"=>"French English Bilingual Visual Dictionary","ImageName"=>"images/6_Cover.png","BarCodeImage"=>"barcode/6_Barcode.png","Languages"=>"French,English","BarCode"=>"9781465459282","DbPath"=>"datafiles/6_BVDTemplate.sqlite","region"=>"2"),
							array("orderId"=>"7","Dictionary"=>"Italian English Bilingual Visual Dictionary","ImageName"=>"images/7_Cover.png","BarCodeImage"=>"barcode/7_Barcode.png","Languages"=>"Italian,English","BarCode"=>"9780241292440","DbPath"=>"datafiles/7_BVDTemplate.sqlite","region"=>"1"),
							array("orderId"=>"8","Dictionary"=>"Italian English Bilingual Visual Dictionary","ImageName"=>"images/8_Cover.png","BarCodeImage"=>"barcode/8_Barcode.png","Languages"=>"Italian,English","BarCode"=>"9781465459305","DbPath"=>"datafiles/8_BVDTemplate.sqlite","region"=>"2"),
							array("orderId"=>"9","Dictionary"=>"Spanish English Bilingual Visual Dictionary","ImageName"=>"images/9_Cover.png","BarCodeImage"=>"barcode/9_Barcode.png","Languages"=>"Spanish,English","BarCode"=>"9780241292433","DbPath"=>"datafiles/9_BVDTemplate.sqlite","region"=>"1"),
							array("orderId"=>"10","Dictionary"=>"Spanish English Bilingual Visual Dictionary","ImageName"=>"images/10_Cover.png","BarCodeImage"=>"barcode/10_Barcode.png","Languages"=>"Spanish,English","BarCode"=>"9781465459312","DbPath"=>"datafiles/10_BVDTemplate.sqlite","region"=>"2")));
							
    $dictionaryArraytest = array("dbversion"=>"1.0","overwritedb"=>"0","databasearray"=>array(array("orderId"=>"1","Dictionary"=>"German English Bilingual Visual Dictionary","ImageName"=>"images/1_Cover.png","BarCodeImage"=>"barcode/1_Barcode.png","Languages"=>"German,English","BarCode"=>"9780241292457","DbPath"=>"datafiles/1_BVDTemplate.sqlite","region"=>"1"),
                         array("orderId"=>"2","Dictionary"=>"German English Bilingual Visual Dictionary","ImageName"=>"images/2_Cover.png","BarCodeImage"=>"barcode/2_Barcode.png","Languages"=>"German","BarCode"=>"9781465459299","DbPath"=>"datafiles/2_BVDTemplate.sqlite","region"=>"2"),
                                                                                              array("orderId"=>"3","Dictionary"=>"Arabic English Bilingual Visual Dictionary","ImageName"=>"images/3_Cover.png","BarCodeImage"=>"barcode/3_Barcode.png","Languages"=>"Arabic,English","BarCode"=>"9780241292464","DbPath"=>"datafiles/3_BVDTemplate.sqlite","region"=>"1"),
                                                                                              array("orderId"=>"4","Dictionary"=>"Arabic English Bilingual Visual Dictionary","ImageName"=>"images/4_Cover.png","BarCodeImage"=>"barcode/4_Barcode.png","Languages"=>"Arabic,English","BarCode"=>"9781465459275","DbPath"=>"datafiles/4_BVDTemplate.sqlite","region"=>"2"),
                                                                                              array("orderId"=>"5","Dictionary"=>"French English Bilingual Visual Dictionary","ImageName"=>"images/5_Cover.png","BarCodeImage"=>"barcode/5_Barcode.png","Languages"=>"French,English","BarCode"=>"9780241287286","DbPath"=>"datafiles/5_BVDTemplate.sqlite","region"=>"1"),
                                                                                              array("orderId"=>"6","Dictionary"=>"French English Bilingual Visual Dictionary","ImageName"=>"images/6_Cover.png","BarCodeImage"=>"barcode/6_Barcode.png","Languages"=>"French,English","BarCode"=>"9781465459282","DbPath"=>"datafiles/6_BVDTemplate.sqlite","region"=>"2"),
                                                                                              array("orderId"=>"7","Dictionary"=>"Italian English Bilingual Visual Dictionary","ImageName"=>"images/7_Cover.png","BarCodeImage"=>"barcode/7_Barcode.png","Languages"=>"Italian,English","BarCode"=>"9780241292440","DbPath"=>"datafiles/7_BVDTemplate.sqlite","region"=>"1"),
                                                                                              array("orderId"=>"8","Dictionary"=>"Italian English Bilingual Visual Dictionary","ImageName"=>"images/8_Cover.png","BarCodeImage"=>"barcode/8_Barcode.png","Languages"=>"Italian,English","BarCode"=>"9781465459305","DbPath"=>"datafiles/8_BVDTemplate.sqlite","region"=>"2"),
                                                                                              array("orderId"=>"9","Dictionary"=>"Spanish English Bilingual Visual Dictionary","ImageName"=>"images/9_Cover.png","BarCodeImage"=>"barcode/9_Barcode.png","Languages"=>"Spanish,English","BarCode"=>"9780241292433","DbPath"=>"datafiles/9_BVDTemplate.sqlite","region"=>"1"),
                                                                                              array("orderId"=>"10","Dictionary"=>"Spanish English Bilingual Visual Dictionary","ImageName"=>"images/10_Cover.png","BarCodeImage"=>"barcode/10_Barcode.png","Languages"=>"Spanish,English","BarCode"=>"9781465459312","DbPath"=>"datafiles/10_BVDTemplate.sqlite","region"=>"2")));
?>
